export const SAVE_SUPPLIER_DATA = "SAVE_SUPPLIER_DATA";
export const GET_SUPPLIER_DATA  = "GET_SUPPLIER_DATA";
export const UPDATE_SUPPLIER_DATA = "UPDATE_SUPPLIER_DATA";
export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";
export const GET_STATE_LIST = "GET_STATE_LIST"
export const GET_CITY_LIST = "GET_CITY_LIST"